export const ACTION_LOAD_SEARCH_HISTORY = "ACTION_LOAD_SEARCH_HISTORY";

export const ACTION_SAVE_SEARCH_HISTORY = "ACTION_SAVE_SEARCH_HISTORY";

export const ACTION_ADD_SEARCH_QUERY = "ACTION_ADD_SEARCH_QUERY";
