export const ACTION_LOAD_IMAGES = "ACTION_LOAD_IMAGES";

export const ACTION_SAVE_IMAGES = "ACTION_SAVE_IMAGES";

export const ACTION_UPDATE_SEARCH_QUERY = "ACTION_UPDATE_SEARCH_QUERY";

export const ACTION_DISPLAY_SPINNER = "ACTION_DISPLAY_SPINNER";

export const ACTION_SELECT_IMAGE = "ACTION_SELECT_IMAGE";

export const ACTION_LIKE_IMAGE = "ACTION_LIKE_IMAGE";

export const ACTION_LOAD_FAVORITE_IMAGES = "ACTION_LOAD_FAVORITE_IMAGES";

export const ACTION_SAVE_FAVORITE_IMAGES = "ACTION_SAVE_FAVORITE_IMAGES";
